### ISSUE TITLE
'Too many redirects' when try following link to docs in README

### ISSUE THREAD

**Issue by willfurnass** [openflighthpc/flight-env#12]
Suggest replacing 

https://use.openflighthpc.org/en/latest/working-with-user-suite/flight-environment.html

with 

https://openflighthpc-use.readthedocs.io/en/latest/working-with-user-suite/flight-environment.html

in the short term.

**Comment by ColonelPanicks** [comment]
Thanks for flagging this @willfurnass! 

We've migrated the documentation over the last few months so the latest usage guidance for Flight Environment is available at - https://docs.openflighthpc.org/hpc_environment_usage/ecosystems/purpose_of_this_documentation/. 

I'll look into getting the links across our READMEs appropriately updated.
