### ISSUE TITLE
Introduce prompt preservation for interactive subshells

### ISSUE THREAD

**Issue by mjtko** [openflighthpc/flight-env#4]
If an interactive subshell is started (`bash -i`), the prompt is overridden by profile scripts but as the Flight system is already active, the active env is not displayed.

We should preserve PS1 changes in flight-env and restore them in the Flight Starter bootstrap script.

**Comment by ColonelPanicks** [comment]
Seeing as this problem hasn't been mentioned in almost a year, doesn't seem like a huge issue/concern (why would someone launch an interactive subshell in a session anyway?). Will reopen if problem reoccurs
